// Generated by gencpp from file anomaly_detector/AnomolyData.msg
// DO NOT EDIT!


#ifndef ANOMALY_DETECTOR_MESSAGE_ANOMOLYDATA_H
#define ANOMALY_DETECTOR_MESSAGE_ANOMOLYDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anomaly_detector
{
template <class ContainerAllocator>
struct AnomolyData_
{
  typedef AnomolyData_<ContainerAllocator> Type;

  AnomolyData_()
    : anomalyStatus(false)
    , timeStamp(0)  {
    }
  AnomolyData_(const ContainerAllocator& _alloc)
    : anomalyStatus(false)
    , timeStamp(0)  {
  (void)_alloc;
    }



   typedef uint8_t _anomalyStatus_type;
  _anomalyStatus_type anomalyStatus;

   typedef uint64_t _timeStamp_type;
  _timeStamp_type timeStamp;





  typedef boost::shared_ptr< ::anomaly_detector::AnomolyData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anomaly_detector::AnomolyData_<ContainerAllocator> const> ConstPtr;

}; // struct AnomolyData_

typedef ::anomaly_detector::AnomolyData_<std::allocator<void> > AnomolyData;

typedef boost::shared_ptr< ::anomaly_detector::AnomolyData > AnomolyDataPtr;
typedef boost::shared_ptr< ::anomaly_detector::AnomolyData const> AnomolyDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anomaly_detector::AnomolyData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anomaly_detector::AnomolyData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace anomaly_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'anomaly_detector': ['/home/pankaj/bmw_ws/src/anomaly_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anomaly_detector::AnomolyData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anomaly_detector::AnomolyData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anomaly_detector::AnomolyData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "032f76a84fd0cd8e143318fdfb84e758";
  }

  static const char* value(const ::anomaly_detector::AnomolyData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x032f76a84fd0cd8eULL;
  static const uint64_t static_value2 = 0x143318fdfb84e758ULL;
};

template<class ContainerAllocator>
struct DataType< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anomaly_detector/AnomolyData";
  }

  static const char* value(const ::anomaly_detector::AnomolyData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   anomalyStatus\n\
uint64 timeStamp\n\
";
  }

  static const char* value(const ::anomaly_detector::AnomolyData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anomalyStatus);
      stream.next(m.timeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnomolyData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anomaly_detector::AnomolyData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anomaly_detector::AnomolyData_<ContainerAllocator>& v)
  {
    s << indent << "anomalyStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.anomalyStatus);
    s << indent << "timeStamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANOMALY_DETECTOR_MESSAGE_ANOMOLYDATA_H
